### ISSUE TITLE
New release with no buffer limit + [u8; 20] digest?

### ISSUE THREAD

**Issue by yyaroshevich** [rylev/const-sha1#10]
Is there any chance new version of crate published which can both compute sha1 at compile time from `ConstBuffer` as well as from slice?
Currently [0.2.0](https://docs.rs/const-sha1/latest/src/const_sha1/lib.rs.html#22) only operate on `ConstBuffer` and has unfortunate limit of `1024` bytes of input.
Version of [0.1.1](https://docs.rs/const-sha1/latest/src/const_sha1/lib.rs.html#22) can operate on arbitrary slices, but has a inconvenient `Digest` definition which has no `bytes()` method to convert `[u32; 5]` -> `[u8; 20]`.
Thanks a lot in advance!

**Comment by rylev** [comment]
Published 0.3.0 to crates.io. Hope that helps!
